version: "3.7"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
      - minio
    expose:
      - 3000
    volumes:
      - ./frontend/:/frontend/

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    depends_on:
      - minio
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://codestrands:codestrands@postgres:5432/codestrands
      REDIS_URL: redis://:codestrands@redis:6379
      DEBUG: "true"
      SECRET_KEY: yaVjiPmcBWeMffDk5jhkLVwLMuQnAe6fCdK5a9jd6v9Ysc3boZnMeAp7AmXV5hnk
      OAUTH_REDIRECT_URI: http://codestrands.local:8000/auth/callback/keycloak
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_URL: ${OAUTH_URL}
    expose:
      - 8000
    volumes:
      - ./backend/:/app/

  redis:
    image: redis:6
    command: redis-server --requirepass codestrands --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis_data/:/data/

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: codestrands
      POSTGRES_USER: codestrands
      POSTGRES_PASSWORD: codestrands
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  minio:
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: codestrands
      MINIO_ROOT_PASSWORD: codestrands
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data/:/data/

  nginx:
    image: nginx:1.21
    depends_on:
      - backend
      # - frontend
      - minio
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf/:ro
